export const REAL_ESTATE_TABS = ['الكل', 'تمليك', 'إيجار', 'مخازن', 'إداري', 'أراضي']

export const FALLBACK_REAL_ESTATE_UNITS = [
  {
    id: 1,
    title: 'شقة تمليك فاخرة - بني سويف الجديدة',
    area: 'بني سويف الجديدة',
    rooms: 3,
    finishing: 'سوبر لوكس',
    areaSize: 120,
    floor: 5,
    price: 2500000,
    image: '/image/medium (1).webp',
    description: 'شقة تمليك فاخرة بتشطيب سوبر لوكس في موقع مميز.',
    category: 'تمليك',
    contactLabel: 'تواصل',
  },
  {
    id: 2,
    title: 'دوبلكس تمليك راقٍ',
    area: 'بني سويف',
    rooms: 4,
    finishing: 'لوكس',
    areaSize: 180,
    floor: 2,
    price: 3500000,
    image: '/image/medium (2).webp',
    description: 'وحدة سكنية واسعة بتقسيم مميز وتشطيب حديث.',
    category: 'تمليك',
    contactLabel: 'تواصل',
  },
  {
    id: 3,
    title: 'شقة إيجار عائلية',
    area: 'بني سويف',
    rooms: 3,
    finishing: 'سوبر لوكس',
    areaSize: 130,
    floor: 4,
    price: 5000,
    image: '/image/medium (4).webp',
    description: 'شقة إيجار عائلية بتشطيب فاخر وموقع حيوي.',
    category: 'إيجار',
    contactLabel: 'تواصل',
  },
  {
    id: 4,
    title: 'مخزن تجاري للبيع',
    area: 'بني سويف',
    rooms: 0,
    finishing: 'نصف تشطيب',
    areaSize: 200,
    floor: 0,
    price: 1500000,
    image: '/image/medium (6).webp',
    description: 'مخزن واسع مناسب للأنشطة التجارية والمخازن المركزية.',
    category: 'مخازن',
    contactLabel: 'تواصل',
  },
  {
    id: 5,
    title: 'شقة إداري للبيع',
    area: 'بني سويف الجديدة',
    rooms: 2,
    finishing: 'لوكس',
    areaSize: 100,
    floor: 3,
    price: 1800000,
    image: '/image/medium (7).webp',
    description: 'وحدة إدارية مناسبة للمكاتب والشركات الناشئة.',
    category: 'إداري',
    contactLabel: 'تواصل',
  },
  {
    id: 6,
    title: 'أرض سكنية مميزة',
    area: 'بني سويف الجديدة',
    rooms: 0,
    finishing: '',
    areaSize: 500,
    floor: 0,
    price: 3000000,
    image: '/image/medium (3).webp',
    description: 'قطعة أرض بمساحة كبيرة في منطقة مناسبة للاستثمار السكني.',
    category: 'أراضي',
    contactLabel: 'تواصل',
  },
]

export const FALLBACK_COURSE_MAP = {
  'surveying-package': {
    id: 'surveying-package',
    title: 'باكدج المساحة (الميزان - التوتال ستيشن)',
    description: 'دورة شاملة في أساسيات المساحة العملية مع تدريب تطبيقي على الأجهزة.',
    duration: '48 ساعة ونصف',
    price: 1500,
    level: 'مبتدئ - متوسط',
    instructor: 'م. محمود أحمد',
    instructorBio: 'مهندس مساحة بخبرة عملية طويلة في التدريب الميداني ورفع المواقع.',
    importance: 'تعتبر دورة المساحة من أهم المهارات الأساسية للمهندسين والفنيين، حيث يتم فيها تعلم كيفية رفع وقياس المواقع بدقة عالية. هذه المهارات ضرورية لكل مشروع بناء أو تطوير عقاري، وتشكل الأساس لعمل المهندسين في الموقع.',
    usefulness: [
      'تدريب عملي مباشر على جهاز الميزان والتوتال ستيشن في أعمال الرفع والتوقيع',
      'تحسين دقة الرفع المساحي للمشاريع الكبرى والصغرى',
      'زيادة فرص العمل في شركات المقاولات والاستثمار العقاري',
      'بناء أساس قوي لتعلم برامج المساحة المتقدمة مثل AutoCAD و Civil 3D',
      'القدرة على قراءة وتحليل الخرائط المساحية بفعالية',
    ],
    content: [
      'مقدمة شاملة في علم المساحة وأقسامه وطرق القياس وأنظمة القياس الأساسية المستخدمة في الموقع.',
      'التعرف على جهاز الميزان وجهاز التوتال ستيشن ومكونات كل جهاز وفكرة العمل والواجهة وكيفية الضبط.',
      'التدرب على القياس بالشريط وحساب المساحات والأحجام وقراءة القامة وأعمال التسوية المختلفة.',
      'تنفيذ الميزانية الطولية والعرضية والشبكية وحساب الكميات باستخدام جهاز الميزان.',
      'التعامل مع البرزم وطرق ربط جهاز التوتال ستيشن والبرامج الداخلية مثل الرفع والتوقيع وغيرها.',
      'الربط بين جهاز التوتال ستيشن والأوتوكاد والبرامج الهندسية مع إدخال البيانات وتصديرها من الجهاز.',
      'تنفيذ مشروع عملي بجهاز الميزان ومشروع متكامل بجهاز التوتال ستيشن والأوتوكاد لتثبيت المهارات.',
    ],
    benefits: [
      'شهادة حضور',
      'تدريب عملي داخل الموقع',
      'ملفات تدريبية جاهزة',
      'متابعة بعد انتهاء الدورة',
    ],
    syllabus: [
      {
        section: 'مبادئ علم المساحة',
        serial: '1',
        topic: 'مفهوم وأهمية علم المساحة',
        duration: 'ساعة',
        note: 'نظري',
      },
      {
        section: 'مبادئ علم المساحة',
        serial: '2',
        topic: 'أقسام علم المساحة',
        duration: 'ساعة ونصف',
        note: 'نظري',
      },
      {
        section: 'مبادئ علم المساحة',
        serial: '3',
        topic: 'مقدمة عن طرق القياس الأولية',
        duration: 'ساعة ونصف',
        note: 'نظري',
      },
      {
        section: 'مبادئ علم المساحة',
        serial: '4',
        topic: 'القياس بالشريط وأنواعه والعدد والأدوات المستخدمة في القياس',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        section: 'مبادئ علم المساحة',
        serial: '5',
        topic: 'أنظمة القياس وبعض التحويلات',
        duration: 'ساعتان',
        note: 'نظري',
      },
      {
        section: 'مبادئ علم المساحة',
        serial: '6',
        topic: 'قياس الأشكال المنتظمة والغير منتظمة',
        duration: 'ساعتان',
        note: 'نظري',
      },
      {
        section: 'مبادئ علم المساحة',
        serial: '7',
        topic: 'حساب المساحات والأحجام للأشكال الهندسية',
        duration: 'ساعتان',
        note: 'نظري',
      },
      {
        section: 'جهاز الميزان (Level)',
        serial: '1',
        topic: 'مفهوم جهاز الميزان ومكوناته وأهميته',
        duration: 'ساعة',
        note: 'نظري',
      },
      {
        section: 'جهاز الميزان (Level)',
        serial: '2',
        topic: 'كيفية ضبط جهاز الميزان والقراءة على القامة',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        section: 'جهاز الميزان (Level)',
        serial: '3',
        topic: 'علم التسوية وأهميته (الميزانية الطولية - العرضية - الشبكية)',
        duration: 'ساعة ونصف',
        note: 'نظري',
      },
      {
        section: 'جهاز الميزان (Level)',
        serial: '4',
        topic: 'الميزانية الطولية',
        duration: 'ساعة ونصف',
        note: 'نظري',
      },
      {
        section: 'جهاز الميزان (Level)',
        serial: '5',
        topic: 'الميزانية الطولية',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        section: 'جهاز الميزان (Level)',
        serial: '6',
        topic: 'الميزانية العرضية',
        duration: 'ساعة ونصف',
        note: 'نظري',
      },
      {
        section: 'جهاز الميزان (Level)',
        serial: '7',
        topic: 'الميزانية العرضية',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        section: 'جهاز الميزان (Level)',
        serial: '8',
        topic: 'الميزانية الشبكية',
        duration: 'ساعة ونصف',
        note: 'نظري',
      },
      {
        section: 'جهاز الميزان (Level)',
        serial: '9',
        topic: 'الميزانية الشبكية',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        section: 'جهاز الميزان (Level)',
        serial: '10',
        topic: 'حساب الكميات',
        duration: 'ساعة ونصف',
        note: 'نظري',
      },
      {
        section: 'جهاز الميزان (Level)',
        serial: '11',
        topic: 'عمل مشروع بجهاز الميزان',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        section: 'جهاز التوتال استيشن (Total Station)',
        serial: '1',
        topic: 'التعريف بالجهاز ومكوناته وأنواعه',
        duration: 'ساعتان',
        note: 'نظري',
      },
      {
        section: 'جهاز التوتال استيشن (Total Station)',
        serial: '2',
        topic: 'فكرة عمل الجهاز (الإحداثيات)',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        section: 'جهاز التوتال استيشن (Total Station)',
        serial: '3',
        topic: 'واجهة الجهاز',
        duration: 'ساعة',
        note: 'عملي',
      },
      {
        section: 'جهاز التوتال استيشن (Total Station)',
        serial: '4',
        topic: 'كيفية ضبط الجهاز (التسامت)',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        section: 'جهاز التوتال استيشن (Total Station)',
        serial: '5',
        topic: 'البرزم وأنواعه',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        section: 'جهاز التوتال استيشن (Total Station)',
        serial: '6',
        topic: 'طرق ربط الجهاز',
        duration: 'ساعة',
        note: 'نظري',
      },
      {
        section: 'جهاز التوتال استيشن (Total Station)',
        serial: '8',
        topic: 'البرامج داخل الجهاز (رفع - توقيع وغيرها)',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        section: 'جهاز التوتال استيشن (Total Station)',
        serial: '9',
        topic: 'طرق ربط الجهاز 2',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        section: 'جهاز التوتال استيشن (Total Station)',
        serial: '10',
        topic: 'العلاقة بين الجهاز والبرامج الهندسية',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        section: 'جهاز التوتال استيشن (Total Station)',
        serial: '11',
        topic: 'إدخال البيانات وتصديرها من الجهاز',
        duration: 'ساعة',
        note: 'عملي',
      },
      {
        section: 'جهاز التوتال استيشن (Total Station)',
        serial: '12',
        topic: 'عمل مشروع بجهاز التوتال استيشن والأوتوكاد',
        duration: '4 ساعات',
        note: 'عملي',
      },
    ],
    image: '/image/Courses/Area package (leveling - total station).jpg',
    whatsappNumber: '01027347377',
  },
  autocad: {
    id: 'autocad',
    title: 'الأوتوكاد',
    description: 'تعلم أساسيات الرسم الهندسي وإخراج اللوحات على برنامج AutoCAD.',
    duration: '20 ساعة',
    price: 700,
    level: 'مبتدئ - متوسط',
    instructor: 'م. سارة محمد',
    instructorBio: 'مدربة برامج هندسية متخصصة في إعداد المسارات التعليمية للمبتدئين.',
    importance: 'برنامج AutoCAD هو المعيار الفني العالمي للرسم الهندسي والمعماري، ويعتبر من أهم البرامج التي يجب على كل مهندس أن يتقنها. الطلب عليه في سوق العمل مرتفع جداً، وهو يستخدم في جميع مقاولات البناء والشركات الهندسية.',
    usefulness: [
      'رسم الخرائط الهندسية والمعمارية بدقة عالية',
      'إعداد لوحات العرض والمخططات بأشكال احترافية',
      'الحصول على وظائف أفضل براتب أعلى في الشركات الهندسية',
      'الاستعداد لتعلم برامج متقدمة مثل Revit و Civil 3D',
      'توثيق وحفظ المشاريع برقم بطريقة منظمة وآمنة',
    ],
    content: [
      'التعريف ببرنامج الأوتوكاد وواجهة العمل وأسلوب استخدام الأدوات الأساسية داخل البرنامج.',
      'التدرب على أوامر الرسم المختلفة وتطبيقها عمليًا على العناصر والخطوط الهندسية.',
      'استخدام أوامر التعديل لتطوير الرسومات والتحكم في مكوناتها بدقة أكبر.',
      'إنشاء الطبقات داخل اللوحة وتنظيم العناصر والمحتوى بطريقة احترافية.',
      'التعرف على بعض الأوامر المستخدمة في أعمال المساحة وربطها ببيئة الرسم داخل الأوتوكاد.',
      'فهم العلاقة بين الأوتوكاد والأجهزة المساحية وكيفية التعامل مع البيانات الناتجة عنها.',
      'إعداد الصيغ التي يتعرف عليها البرنامج وإدخال البيانات وتصديرها من البرنامج بصورة صحيحة.',
    ],
    benefits: [
      'مشاريع تطبيقية',
      'شهادة حضور',
      'ملفات تدريبية',
      'دعم فني بعد الدورة',
    ],
    syllabus: [
      {
        serial: '1',
        topic: 'التعريف بالبرنامج وواجهته',
        duration: 'ساعة',
        note: 'نظري',
      },
      {
        serial: '2',
        topic: 'أوامر الرسم',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        serial: '3',
        topic: 'أوامر الرسم',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        serial: '4',
        topic: 'أوامر التعديل',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        serial: '5',
        topic: 'أوامر التعديل',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        serial: '6',
        topic: 'عمل الطبقات داخل اللوحة',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        serial: '7',
        topic: 'بعض الأوامر المستخدمة في أعمال المساحة',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        serial: '8',
        topic: 'العلاقة بين الأوتوكاد والأجهزة المساحية',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        serial: '9',
        topic: 'كيفية عمل الصيغ التي يتعرف عليها البرنامج وإدخال البيانات وتصديرها من البرنامج',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
    ],
    image: '/image/Courses/Auto cat.jpeg',
    whatsappNumber: '01027347377',
  },
  'civil-3d': {
    importance: 'Civil 3D هو البرنامج الأشهر والأكثر استخداماً في مشاريع الطرق والبنية التحتية والمشاريع الكبرى. يُستخدم من قبل أكبر شركات المقاولات والهندسة، ويتطلبه معظم المهندسين المدنيين في سوق العمل الحديث.',
    usefulness: [
      'تصميم شبكات الطرق والبنية التحتية بسهولة واحترافية',
      'حساب الكميات والتكاليف بدقة عالية',
      'إنشاء التقارير والمجسمات ثلاثية الأبعاد للمشاريع',
      'توظيف أفضل في المشاريع الحكومية والخاصة الكبرى',
      'اكتساب خبرة عملية في تصميم المشاريع الفعلية',
    ],
    id: 'civil-3d',
    title: 'سيفيل 3D',
    description: 'دورة متخصصة في تطبيقات الطرق والبنية التحتية باستخدام Civil 3D.',
    duration: '20 ساعة',
    price: 700,
    level: 'متوسط',
    instructor: 'د. أحمد علي',
    instructorBio: 'متخصص في التصميم المدني والمساحي وإعداد المشاريع التطبيقية.',
    content: [
      'التعريف ببرنامج Civil 3D وواجهة العمل وأسلوب التعامل مع ملفاته وأوامره الأساسية.',
      'التدرب على أوامر الرسم داخل البرنامج وتطبيقها على عناصر التصميم المختلفة.',
      'التعرف على أوامر التعديل والتحكم في العناصر والرسومات بشكل عملي.',
      'إدخال النقط وتصديرها والتعديل عليها وربط البيانات المساحية داخل البرنامج.',
      'تصميم الطرق وعمل البروفايلات الطولية والعرضية ومتابعة مسار المشروع.',
      'حساب الكميات بأكثر من طريقة وفهم العلاقة بين البرنامج والأجهزة المساحية.',
      'إعداد الصيغ التي يتعرف عليها البرنامج وإدخال البيانات وتصديرها بصورة صحيحة.',
    ],
    benefits: [
      'مشروعات تطبيقية',
      'ملفات تدريبية قابلة للتعديل',
      'متابعة بعد الدورة',
    ],
    syllabus: [
      {
        serial: '1',
        topic: 'التعريف بالبرنامج وواجهته',
        duration: 'ساعة',
        note: 'نظري',
      },
      {
        serial: '2',
        topic: 'أوامر الرسم',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        serial: '3',
        topic: 'أوامر الرسم',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        serial: '4',
        topic: 'أوامر التعديل',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        serial: '5',
        topic: 'إدخال النقط وتصديرها والتعديل عليها',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        serial: '6',
        topic: 'تصميم الطرق وعمل البروفايلات',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        serial: '7',
        topic: 'حساب الكميات بأكثر من طريقة',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        serial: '8',
        topic: 'العلاقة بين البرنامج والأجهزة المساحية',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        serial: '9',
        topic: 'كيفية عمل الصيغ التي يتعرف عليها البرنامج وإدخال البيانات وتصديرها من البرنامج',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
    ],
    image: '/image/Courses/Civil 3D.jpg',
    whatsappNumber: '01027347377',
  },
  '3d-max': {
    importance: '3D Max هو البرنامج الرائد عالمياً في الإظهار المعماري والنمذجة ثلاثية الأبعاد. يستخدمه أفضل المصممين والعاملين في صناعة الإظهار، ويساعد في تقديم المشاريع بطريقة احترافية تجذب المستثمرين والعملاء.',
    usefulness: [
      'إنتاج صور معمارية احترافية تبهر الاستثمارين والعملاء',
      'عرض التصاميم بشكل واقعي قبل البدء في البناء',
      'خلق محتوى بصري عالي الجودة للدعاية والتسويق',
      'الحصول على فرص عمل في مكاتب التصميم والشركات الهندسية الكبرى',
      'تطوير مهارات الإبداع والتصميم الفني',
    ],
    id: '3d-max',
    title: '3D Max',
    description: 'تعلم النمذجة الثلاثية والإظهار المعماري لعرض المشاريع بصورة احترافية.',
    duration: '20 ساعة',
    price: 2000,
    level: 'مبتدئ - متوسط',
    instructor: 'م. يوسف محمود',
    instructorBio: 'مصمم متخصص في الإظهار المعماري وإنتاج المشاهد البصرية.',
    content: [
      'مقدمة في البرنامج وأدوات العمل',
      'النمذجة الثلاثية الأساسية',
      'الخامات والإضاءة',
      'إعداد الريندر النهائي',
    ],
    benefits: [
      'شهادة حضور',
      'أمثلة عملية',
      'مكتبة خامات أساسية',
    ],
    image: '/image/Courses/3D Max.jpeg',
    whatsappNumber: '01027347377',
  },
  revit: {
    id: 'revit',
    title: 'الريفيت',
    description: 'دورة عملية في Revit ونمذجة المشاريع باستخدام BIM.',
    duration: '20 ساعة',
    price: 2000,
    level: 'مبتدئ - متوسط',
    instructor: 'م. نورا أحمد',
    instructorBio: 'مهندسة متخصصة في نمذجة المعلومات BIM وإدارة ملفات المشاريع.',
    importance: 'Revit والتكنولوجيا BIM تُمثل مستقبل الصناعة الهندسية والمعمارية. الشركات الكبرى والحكومات تتطلب العمل بنظام BIM، وهذا البرنامج يُعتبر الأساس لأي مشروع حديث. إتقان Revit يفتح آفاقاً وظيفية واسعة.',
    usefulness: [
      'تصميم المشاريع باستخدام نمذجة المعلومات المتكاملة',
      'تنسيق العمل بين التخصصات المختلفة بكفاءة عالية',
      'إعداد الكميات والجداول تلقائياً وبدقة',
      'العمل في المشاريع الكبرى والعملاقة كمهندس BIM',
      'تقليل الأخطاء والنزاعات بين فرق العمل المختلفة',
    ],
    content: [
      'مقدمة في Revit وBIM',
      'إنشاء النماذج والعناصر',
      'إعداد اللوحات والجداول',
      'تنسيق المشروع وتصديره',
    ],
    benefits: [
      'شهادة حضور',
      'مكتبة عناصر أساسية',
      'متابعة بعد انتهاء الدورة',
    ],
    image: '/image/Courses/Revit.jpg',
    whatsappNumber: '01027347377',
  },
  'arc-gis': {
    id: 'arc-gis',
    title: 'نظم المعلومات الجغرافية (Arc GIS)',
    description: 'دورة متخصصة في نظم المعلومات الجغرافية وتحليل البيانات المكانية باستخدام Arc GIS من الأساسيات حتى تنفيذ مشروع تطبيقي متكامل.',
    duration: '15 ساعة',
    price: null,
    level: 'مبتدئ - متوسط',
    instructor: 'فريق إعمار للتدريب الهندسي',
    instructorBio: 'مسار تدريبي يجمع بين الشرح النظري والتطبيق العملي على Arc GIS لإعداد الخرائط وتحليل البيانات المكانية باحترافية.',
    importance: 'دورة Arc GIS تمنح الطالب أساسًا قويًا في نظم المعلومات الجغرافية، وتساعده على فهم التحليل المكاني وإدارة البيانات والخرائط الرقمية بصورة عملية يحتاجها سوق العمل في المساحة والتخطيط والمشروعات.',
    usefulness: [
      'فهم مبادئ نظم المعلومات الجغرافية وربطها بالاستخدامات العملية في المساحة والتحليل المكاني.',
      'التدرب على واجهة Arc GIS وأدواته الأساسية لإضافة البيانات والرسم وتجهيز الطبقات.',
      'اكتساب قدرة عملية على إخراج الخرائط وتصحيحها والتعامل مع قواعد البيانات المكانية.',
      'تنفيذ مشروع تدريبي يساعد الطالب على استخدام البرنامج بثقة بعد انتهاء الكورس.',
    ],
    content: [
      'تعريف ومفهوم نظم المعلومات الجغرافية (GIS) وأهميتها في المجالات الهندسية والخدمية.',
      'مكونات نظم المعلومات الجغرافية ووظائفها ومجالات استخدامها وأهم البرامج المرتبطة بها.',
      'التعرف على برنامج Arc GIS وواجهته ومكوناته الأساسية وكيفية بدء العمل عليه.',
      'إضافة قواعد البيانات والرسم وإظهار الألوان وإخراج الخرائط وتصحيحها بشكل منظم.',
      'التدرب على بعض الأوامر المستخدمة في المساحة وإدخال البيانات وتصديرها من البرنامج.',
      'تنفيذ مشروع عملي كامل باستخدام Arc GIS لتثبيت المهارات المكتسبة خلال الكورس.',
    ],
    benefits: [
      'تدرج واضح من الشرح النظري إلى التطبيق العملي داخل البرنامج.',
      'تطبيقات مباشرة على إدخال البيانات وتجهيز الخرائط وإخراجها بصورة احترافية.',
      'التعرف على أوامر ومهام مهمة يحتاجها الطالب في الأعمال المساحية والمكانية.',
      'مشروع ختامي يساعد الطالب على بناء خبرة عملية قابلة للتطبيق بعد الكورس.',
    ],
    syllabus: [
      {
        serial: '1',
        topic: 'تعريف ومفهوم نظم المعلومات الجغرافية',
        duration: 'ساعة',
        note: 'نظري',
      },
      {
        serial: '2',
        topic: 'أهمية نظم المعلومات الجغرافية',
        duration: 'ساعة ونصف',
        note: 'نظري',
      },
      {
        serial: '3',
        topic: 'مكونات نظم المعلومات الجغرافية',
        duration: 'ساعة',
        note: 'نظري',
      },
      {
        serial: '4',
        topic: 'وظائف نظم المعلومات الجغرافية ومجالات استخدامها',
        duration: 'ساعة',
        note: 'نظري',
      },
      {
        serial: '5',
        topic: 'أهم البرامج المستخدمة في نظم المعلومات الجغرافية',
        duration: 'ساعة',
        note: 'نظري',
      },
      {
        serial: '6',
        topic: 'برنامج Arc GIS: ما هو وواجهته ومكوناته',
        duration: 'ساعة',
        note: 'عملي',
      },
      {
        serial: '8',
        topic: 'كيفية إضافة قواعد البيانات والرسم وإظهار الألوان وإخراج وتصحيح الخرائط',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        serial: '9',
        topic: 'أهم البرامج المساعدة للبرنامج',
        duration: 'ساعة ونصف',
        note: 'عملي',
      },
      {
        serial: '10',
        topic: 'بعض الأوامر المستخدمة في المساحة',
        duration: 'ساعتان',
        note: 'عملي',
      },
      {
        serial: '11',
        topic: 'إدخال البيانات وتصديرها من البرنامج',
        duration: 'ساعة',
        note: 'عملي',
      },
      {
        serial: '12',
        topic: 'عمل مشروع ببرنامج Arc GIS',
        duration: 'ساعتان',
        note: 'عملي',
      },
    ],
    image: '/image/Courses/arc gls.jpg',
    whatsappNumber: '01027347377',
  },
}

export const FALLBACK_COURSE_LIST = Object.values(FALLBACK_COURSE_MAP)

export const FALLBACK_CURRENT_PROJECTS = [
  {
    id: 1,
    title: 'أبراج إعمار',
    location: 'بني سويف - حي الرمض - خلف أرض الطيارين',
    type: 'سكني',
    status: 'قيد الإنشاء',
    description: 'مجمع أبراج فاخر بتصميم عصري وخدمات متكاملة.',
    cardNote: '4 أبراج منفصلة',
    cardUnitsMix: 'شقق سكنية - شقق إدارية - محلات - بدروم',
    image: '/image/Our current projects/Emaar Towers/Emaar Towers (1).jpg',
    images: [
      '/image/Our current projects/Emaar Towers/Emaar Towers (1).jpg',
      '/image/Our current projects/Emaar Towers/Emaar Towers (2).jpg',
      '/image/Our current projects/Emaar Towers/Emaar Towers (3).jpg',
      '/image/Our current projects/Emaar Towers/Emaar Towers (4).jpg',
      '/image/Our current projects/Emaar Towers/Emaar Towers (5).jpg',
      '/image/Our current projects/Emaar Towers/Emaar Towers Split (1).jpg',
      '/image/Our current projects/Emaar Towers/Emaar Towers Split (2).jpg',
      '/image/Our current projects/Emaar Towers/Emaar Towers Split (3).jpg',
      '/image/Our current projects/Emaar Towers/Emaar Towers Split (4).jpg',
      '/image/Our current projects/Emaar Towers/Emaar Towers Split (5).jpg',
    ],
    progress: 75,
    floors: 7,
  },
  {
    id: 2,
    title: 'رويال سيتي',
    location: 'امتداد الرمض خلف أرض الطيارين أمام أبراج إعمار',
    type: 'سكني',
    status: 'قيد الإنشاء',
    description: 'مجمع سكني راقٍ بتشطيبات فاخرة ومرافق متكاملة.',
    cardNote: '4 شقق بالدور',
    image: '/image/Our current projects/Royal city/royal city (1).jpg',
    images: [
      '/image/Our current projects/Royal city/royal city (1).jpg',
      '/image/Our current projects/Royal city/royal city (2).jpg',
      '/image/Our current projects/Royal city/royal city (3).jpg',
      '/image/Our current projects/Royal city/Royal City Apartment (1).jpg',
      '/image/Our current projects/Royal city/Royal City Apartment (2).jpg',
      '/image/Our current projects/Royal city/Royal City Apartment (3).jpg',
      '/image/Our current projects/Royal city/Royal City Apartment (4).jpg',
    ],
    progress: 55,
    floors: 7,
  },
]

export const FALLBACK_PREVIOUS_PROJECTS = [
  {
    id: 'beni-suef-post',
    title: 'مبنى البريد - بنى سويف',
    location: 'بنى سويف',
    type: 'حكومي',
    status: 'مكتمل',
    description: 'مبنى البريد ودراسات إسلامية في بنى سويف',
    image: '/image/Beni Suef Post Office, Islamic Studies/Post office (1).jpg',
    images: [
      '/image/Beni Suef Post Office, Islamic Studies/Post office (1).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (2).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (3).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (4).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (5).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (6).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (7).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (8).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (9).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (10).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (11).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (12).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (13).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (14).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (15).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (16).jpg',
      '/image/Beni Suef Post Office, Islamic Studies/Post office (17).jpg',
    ],
  },
  {
    id: 'al-harbi',
    title: 'شركة الحربي',
    location: 'مصر',
    type: 'تجاري',
    status: 'مكتمل',
    description: 'مشروع شركة الحربي',
    image: '/image/Al-Harbi Company/Al-Harbi Company (1).jpg',
    images: [
      '/image/Al-Harbi Company/Al-Harbi Company (1).jpg',
      '/image/Al-Harbi Company/Al-Harbi Company (2).jpg',
      '/image/Al-Harbi Company/Al-Harbi Company (3).jpg',
      '/image/Al-Harbi Company/Al-Harbi Company (4).jpg',
      '/image/Al-Harbi Company/Al-Harbi Company (5).jpg',
      '/image/Al-Harbi Company/Al-Harbi Company (6).jpg',
      '/image/Al-Harbi Company/Al-Harbi Company (7).jpg',
    ],
  },
  {
    id: 'workers-university',
    title: 'البوابات - الجامعة العمالية',
    location: 'مصر',
    type: 'تعليمي',
    status: 'مكتمل',
    description: 'بوابات الجامعة العمالية',
    image: "/image/البوبات/الجامعة العمالية/Workers' University Gates (1).JPG",
    images: [
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (1).JPG",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (2).JPG",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (3).JPG",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (4).jpg",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (5).jpg",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (6).jpg",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (7).jpg",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (8).jpg",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (9).jpg",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (10).jpg",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (11).jpg",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (12).jpg",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (13).jpg",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (14).JPG",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (15).JPG",
      "/image/البوبات/الجامعة العمالية/Workers' University Gates (16).JPG",
    ],
  },
  {
    id: 'beni-suef-university',
    title: 'البوابات - جامعة بنى سويف',
    location: 'بنى سويف',
    type: 'تعليمي',
    status: 'مكتمل',
    description: 'بوابات جامعة بنى سويف',
    image: '/image/البوبات/جامعة بنى سويف/Beni Suef University Gates (1).JPG',
    images: [
      '/image/البوبات/جامعة بنى سويف/Beni Suef University Gates (1).JPG',
      '/image/البوبات/جامعة بنى سويف/Beni Suef University Gates (2).JPG',
      '/image/البوبات/جامعة بنى سويف/Beni Suef University Gates (3).JPG',
      '/image/البوبات/جامعة بنى سويف/Beni Suef University Gates (4).JPG',
    ],
  },
]

export const FALLBACK_PREVIOUS_PROJECT_EMAAR_IMAGES = [
  '/image/Our projects/Our projects  Emaar tower (12).jpg',
  '/image/Our projects/Our projects  Emaar tower (13).jpg',
  '/image/Our projects/Our projects  Emaar tower (14).jpg',
  '/image/Our projects/Our projects  Emaar tower (15).jpg',
  '/image/Our projects/Our projects  Emaar tower (16).jpg',
  '/image/Our projects/Our projects  Emaar tower (17).jpg',
  '/image/Our projects/Our projects  Emaar tower (18).jpg',
  '/image/Our projects/Our projects  Emaar tower (19).jpg',
  '/image/Our projects/Our projects  Emaar tower (20).jpg',
  '/image/Our projects/Our projects  Emaar tower (21).jpg',
  '/image/Our projects/Our projects  Emaar tower (22).jpg',
  '/image/Our projects/Our projects  Emaar tower (23).jpg',
  '/image/Our projects/Our projects  Emaar tower (24).jpg',
  '/image/Our projects/Our projects  Emaar tower (25).jpg',
  '/image/Our projects/Our projects  Emaar tower (26).jpg',
]

export const FALLBACK_PREVIOUS_PROJECT_GALLERY_IMAGES = [
  '/image/Our projects/Our projects (1).jpg',
  '/image/Our projects/Our projects (2).jpg',
  '/image/Our projects/Our projects (3).jpg',
  '/image/Our projects/Our projects (4).jpg',
  '/image/Our projects/Our projects (5).jpg',
  '/image/Our projects/Our projects (6).jpg',
  '/image/Our projects/Our projects (7).jpg',
  '/image/Our projects/Our projects (8).jpg',
  '/image/Our projects/Our projects (9).jpg',
  '/image/Our projects/Our projects (10).jpg',
  '/image/Our projects/Our projects (11).jpg',
  '/image/Our projects/Our projects (12).jpg',
  '/image/Our projects/Our projects (13).jpg',
  '/image/Our projects/Our projects (14).jpg',
  '/image/Our projects/Our projects (15).jpg',
  '/image/Our projects/Our projects (16).jpg',
  '/image/Our projects/Our projects (17).jpg',
  '/image/Our projects/Our projects (18).jpg',
  '/image/Our projects/Our projects (19).jpg',
  '/image/Our projects/Our projects (20).jpg',
  '/image/Our projects/Our projects (21).jpg',
  '/image/Our projects/Our projects (22).jpg',
  '/image/Our projects/Our projects (23).jpg',
  '/image/Our projects/Our projects (24).jpg',
  '/image/Our projects/Our projects (25).jpg',
  '/image/Our projects/Our projects (26).jpg',
  '/image/Our projects/Our projects (27).jpg',
  '/image/Our projects/Our projects (28).jpg',
  '/image/Our projects/Our projects (29).jpg',
  '/image/Our projects/Our projects (30).jpg',
]
